### ISSUE TITLE
Instructions on how to patch

### ISSUE THREAD

**Issue by twoelw** [quintenvandamme/unsafeexambrowser#2]
Would be very nice if there were instructions on how to build this, just in case this gets taken down or maybe a new version comes out so we can patch it ourselves

Prachtig werk ;))

**Comment by quintenvandamme** [comment]
I think building a installer is the better way to go. Adding a new version can be done with ease with git rebase. I do want to make it clear however which version of safe exam browser it is on so i will name newer builds to the safe exam browser and not to my own made up ones (like unsafeeaxmbrowser 2.0).

Also keep in mind that tons of different files are patched so unless you want to replace all those file this is not a good way to do so.

Right now everything is bundled in a installer and is build by github actions but it also bundels dll's from older versions that it needs, this means installers build from github actions, and building it locally are broken right now.

**Comment by twoelw** [comment]
Ahh alright, problem is with the other projects for some reason the owners puts zero documentation on the project and abandons it which is bad
